CREATE TABLE roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id    BIGINT       NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(20),
    password   VARCHAR(255) NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE specialties (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    min_age     INT          NOT NULL DEFAULT 0,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_specialties PRIMARY KEY (id)
);

CREATE TABLE patients (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT        NOT NULL,
    date_of_birth DATE          NOT NULL,
    weight_lbs    DECIMAL(6, 2),
    height_cm     DECIMAL(5, 2),
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

CREATE TABLE doctors (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT NOT NULL,
    specialty_id     BIGINT NOT NULL,
    consultation_fee INT    NOT NULL DEFAULT 0,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_doctors PRIMARY KEY (id)
);

CREATE TABLE doctors_schedule (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    doctor_id   BIGINT      NOT NULL,
    day_of_week VARCHAR(10) NOT NULL,
    shift_start TIME        NOT NULL,
    shift_end   TIME        NOT NULL,
    CONSTRAINT pk_doctors_schedule PRIMARY KEY (id)
);

CREATE TABLE appointments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    patient_id       BIGINT      NOT NULL,
    doctor_id        BIGINT      NOT NULL,
    appointment_date TIMESTAMP   NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    meeting_link     VARCHAR(500),
    rating           INT,
    version          INT         NOT NULL DEFAULT 0,
    created_at       TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_appointments PRIMARY KEY (id),
    CONSTRAINT chk_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE payments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_id        BIGINT      NOT NULL,
    amount_cents          INT         NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    stripe_transaction_id VARCHAR(255),
    created_at            TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMP   NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_payments PRIMARY KEY (id)
);

CREATE TABLE medical_notes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_id BIGINT    NOT NULL,
    notes          TEXT      NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_medical_notes PRIMARY KEY (id)
);

CREATE TABLE attachments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_id BIGINT       NOT NULL,
    uploaded_by    BIGINT       NOT NULL,
    document_type  VARCHAR(50),
    file_name      VARCHAR(255) NOT NULL,
    file_url       VARCHAR(500) NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_attachments PRIMARY KEY (id)
);

CREATE TABLE prescriptions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_id     BIGINT    NOT NULL,
    medication_details TEXT      NOT NULL,
    hash_signature     VARCHAR(255) NOT NULL,
    uses_remaining     INT       NOT NULL DEFAULT 3,
    expiration_date    TIMESTAMP NOT NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_prescriptions PRIMARY KEY (id)
);

-- Foreign Keys
ALTER TABLE users ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE patients ADD CONSTRAINT fk_patients_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE doctors ADD CONSTRAINT fk_doctors_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE doctors ADD CONSTRAINT fk_doctors_specialty FOREIGN KEY (specialty_id) REFERENCES specialties (id);
ALTER TABLE doctors_schedule ADD CONSTRAINT fk_schedule_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors (id);
ALTER TABLE payments ADD CONSTRAINT fk_payments_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id);
ALTER TABLE medical_notes ADD CONSTRAINT fk_notes_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id);
ALTER TABLE attachments ADD CONSTRAINT fk_attachments_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id);
ALTER TABLE attachments ADD CONSTRAINT fk_attachments_user FOREIGN KEY (uploaded_by) REFERENCES users (id);
ALTER TABLE prescriptions ADD CONSTRAINT fk_prescriptions_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id);

-- Unique Constraints
ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);
ALTER TABLE patients ADD CONSTRAINT uc_patients_user UNIQUE (user_id);
ALTER TABLE doctors ADD CONSTRAINT uc_doctors_user UNIQUE (user_id);

-- Seed Data
INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN'), ('ROLE_DOCTOR'), ('ROLE_PATIENT');

INSERT INTO specialties (name, description, min_age, is_active) VALUES
    ('Cardiología', 'Enfermedades del corazón y sistema cardiovascular', 18, TRUE),
    ('Pediatría', 'Atención médica para niños y adolescentes', 0, TRUE),
    ('Dermatología', 'Enfermedades de la piel', 5, TRUE),
    ('Neurología', 'Trastornos del sistema nervioso', 14, TRUE),
    ('Medicina General', 'Atención médica primaria', 0, TRUE);

-- Admin user: admin@telemedicina.com / Admin1234!
INSERT INTO users (role_id, first_name, last_name, email, phone, password, is_active)
VALUES (1, 'Admin', 'Sistema', 'admin@telemedicina.com', '77777777',
        '$2b$10$d/W5ZZF3RLbDgygJKEC1suTVAOLYz.8E6VRroPcaJWF7hkyCl0Nki', TRUE);